import { Request, Response, NextFunction } from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { validationResult } from 'express-validator';
import { ApiError } from '../middleware/errorHandler';
import { logger } from '../utils/logger';

export class AuthController {
  async login(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        const error = new Error('Validation failed') as ApiError;
        error.statusCode = 400;
        return next(error);
      }

      const { email, password } = req.body;

      // In a real app, you would query the database here
      // For now, we'll use mock data
      const user = {
        id: '1',
        email: 'user@example.com',
        password: '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        firstName: 'John',
        lastName: 'Doe',
        role: 'user',
        isActive: true,
      };

      if (email !== user.email) {
        const error = new Error('Invalid credentials') as ApiError;
        error.statusCode = 401;
        return next(error);
      }

      const isPasswordValid = await bcrypt.compare(password, user.password);
      if (!isPasswordValid) {
        const error = new Error('Invalid credentials') as ApiError;
        error.statusCode = 401;
        return next(error);
      }

      if (!user.isActive) {
        const error = new Error('Account is deactivated') as ApiError;
        error.statusCode = 401;
        return next(error);
      }

      const token = jwt.sign(
        { id: user.id, email: user.email, role: user.role },
        process.env.JWT_SECRET!,
        { expiresIn: '24h' }
      );

      const refreshToken = jwt.sign(
        { id: user.id },
        process.env.JWT_REFRESH_SECRET!,
        { expiresIn: '7d' }
      );

      logger.info(`User ${user.email} logged in successfully`);

      res.json({
        success: true,
        data: {
          user: {
            id: user.id,
            email: user.email,
            firstName: user.firstName,
            lastName: user.lastName,
            role: user.role,
            isActive: user.isActive,
          },
          token,
          refreshToken,
          expiresIn: 86400, // 24 hours in seconds
        },
        message: 'Login successful',
      });
    } catch (error) {
      next(error);
    }
  }

  async register(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        const error = new Error('Validation failed') as ApiError;
        error.statusCode = 400;
        return next(error);
      }

      const { email, password, firstName, lastName } = req.body;

      // Check if user already exists (in a real app, query database)
      // For now, we'll just simulate this
      const existingUser = null; // Would query database here

      if (existingUser) {
        const error = new Error('User already exists') as ApiError;
        error.statusCode = 409;
        return next(error);
      }

      // Hash password
      const hashedPassword = await bcrypt.hash(password, 12);

      // Create user (in a real app, save to database)
      const newUser = {
        id: '2', // Would be generated by database
        email,
        password: hashedPassword,
        firstName,
        lastName,
        role: 'user',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      const token = jwt.sign(
        { id: newUser.id, email: newUser.email, role: newUser.role },
        process.env.JWT_SECRET!,
        { expiresIn: '24h' }
      );

      const refreshToken = jwt.sign(
        { id: newUser.id },
        process.env.JWT_REFRESH_SECRET!,
        { expiresIn: '7d' }
      );

      logger.info(`New user registered: ${email}`);

      res.status(201).json({
        success: true,
        data: {
          user: {
            id: newUser.id,
            email: newUser.email,
            firstName: newUser.firstName,
            lastName: newUser.lastName,
            role: newUser.role,
            isActive: newUser.isActive,
          },
          token,
          refreshToken,
          expiresIn: 86400,
        },
        message: 'Registration successful',
      });
    } catch (error) {
      next(error);
    }
  }

  async logout(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      // In a real app, you might want to blacklist the token
      logger.info(`User logged out`);
      
      res.json({
        success: true,
        message: 'Logout successful',
      });
    } catch (error) {
      next(error);
    }
  }

  async getCurrentUser(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      // In a real app, you would fetch user data from database
      const user = {
        id: req.user?.id,
        email: req.user?.email,
        firstName: 'John',
        lastName: 'Doe',
        role: req.user?.role,
        isActive: true,
      };

      res.json({
        success: true,
        data: user,
        message: 'User data retrieved successfully',
      });
    } catch (error) {
      next(error);
    }
  }

  async updateProfile(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        const error = new Error('Validation failed') as ApiError;
        error.statusCode = 400;
        return next(error);
      }

      // In a real app, you would update the user in the database
      const updatedUser = {
        id: req.user?.id,
        email: req.user?.email,
        ...req.body,
        updatedAt: new Date().toISOString(),
      };

      res.json({
        success: true,
        data: updatedUser,
        message: 'Profile updated successfully',
      });
    } catch (error) {
      next(error);
    }
  }

  async changePassword(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { currentPassword, newPassword } = req.body;

      // In a real app, you would verify the current password and update
      logger.info(`Password changed for user ${req.user?.id}`);

      res.json({
        success: true,
        message: 'Password changed successfully',
      });
    } catch (error) {
      next(error);
    }
  }

  async forgotPassword(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { email } = req.body;

      // In a real app, you would send a password reset email
      logger.info(`Password reset requested for ${email}`);

      res.json({
        success: true,
        message: 'Password reset email sent',
      });
    } catch (error) {
      next(error);
    }
  }

  async resetPassword(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { token, newPassword } = req.body;

      // In a real app, you would verify the token and update the password
      logger.info(`Password reset completed`);

      res.json({
        success: true,
        message: 'Password reset successfully',
      });
    } catch (error) {
      next(error);
    }
  }

  async verifyEmail(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { token } = req.body;

      // In a real app, you would verify the email token
      logger.info(`Email verified`);

      res.json({
        success: true,
        message: 'Email verified successfully',
      });
    } catch (error) {
      next(error);
    }
  }

  async resendVerification(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { email } = req.body;

      // In a real app, you would send a verification email
      logger.info(`Verification email resent to ${email}`);

      res.json({
        success: true,
        message: 'Verification email sent',
      });
    } catch (error) {
      next(error);
    }
  }
}
